// Code generated by hand. DO NOT EDIT.
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *Widget) DeepCopyInto(out *Widget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy creates a deep copy of the Widget.
func (in *Widget) DeepCopy() *Widget {
	if in == nil {
		return nil
	}
	out := new(Widget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a deep copy as runtime.Object.
func (in *Widget) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// DeepCopyInto copies the receiver into out.
func (in *WidgetSpec) DeepCopyInto(out *WidgetSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of the WidgetSpec.
func (in *WidgetSpec) DeepCopy() *WidgetSpec {
	if in == nil {
		return nil
	}
	out := new(WidgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *WidgetList) DeepCopyInto(out *WidgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Widget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of the WidgetList.
func (in *WidgetList) DeepCopy() *WidgetList {
	if in == nil {
		return nil
	}
	out := new(WidgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a deep copy as runtime.Object.
func (in *WidgetList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// DeepCopyInto copies the receiver into out.
func (in *WidgetSet) DeepCopyInto(out *WidgetSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy creates a deep copy of the WidgetSet.
func (in *WidgetSet) DeepCopy() *WidgetSet {
	if in == nil {
		return nil
	}
	out := new(WidgetSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a deep copy as runtime.Object.
func (in *WidgetSet) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// DeepCopyInto copies the receiver into out.
func (in *WidgetSetSpec) DeepCopyInto(out *WidgetSetSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of the WidgetSetSpec.
func (in *WidgetSetSpec) DeepCopy() *WidgetSetSpec {
	if in == nil {
		return nil
	}
	out := new(WidgetSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *WidgetSetStatus) DeepCopyInto(out *WidgetSetStatus) {
	*out = *in
}

// DeepCopy creates a deep copy of the WidgetSetStatus.
func (in *WidgetSetStatus) DeepCopy() *WidgetSetStatus {
	if in == nil {
		return nil
	}
	out := new(WidgetSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *WidgetSetList) DeepCopyInto(out *WidgetSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WidgetSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of the WidgetSetList.
func (in *WidgetSetList) DeepCopy() *WidgetSetList {
	if in == nil {
		return nil
	}
	out := new(WidgetSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a deep copy as runtime.Object.
func (in *WidgetSetList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}
